
  
#spring:
#    application:
#      name: customer
#   
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always   
        

resilience4j:
  circuitbreaker:
    instances:
        customer:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 20000
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED